# Generated by Django 4.2.15 on 2024-08-18 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=15)),
                ('operating_system', models.CharField(max_length=255)),
                ('cpu_allocation', models.CharField(max_length=255)),
                ('ram_allocation', models.CharField(max_length=255)),
                ('disk_allocation', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('permissions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.servicesystem')),
            ],
        ),
        migrations.CreateModel(
            name='ScalingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scaling_policy', models.TextField()),
                ('auto_scaling_trigger', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('service_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.servicesystem')),
            ],
        ),
        migrations.CreateModel(
            name='Runbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_command', models.TextField()),
                ('verify_command', models.TextField()),
                ('upgrade_command', models.TextField()),
                ('rollback_command', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.servicesystem')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField()),
                ('protocol', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.application')),
                ('service_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.servicesystem')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns', models.CharField(max_length=255)),
                ('gateway', models.CharField(max_length=255)),
                ('subnet', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.servicesystem')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('service_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.servicesystem')),
            ],
        ),
        migrations.CreateModel(
            name='LoggingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_file_path', models.CharField(max_length=1024)),
                ('log_level', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.servicesystem')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=1024)),
                ('criteria', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.servicesystem')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.servicesystem')),
            ],
        ),
        migrations.CreateModel(
            name='DisasterRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_plan', models.TextField()),
                ('backup_locations', models.TextField()),
                ('testing_schedule', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.servicesystem')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('service_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.servicesystem')),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('service_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.servicesystem')),
            ],
        ),
        migrations.CreateModel(
            name='Containerization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_runtime', models.CharField(max_length=255)),
                ('orchestration_tool', models.CharField(max_length=255)),
                ('image_info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('service_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.servicesystem')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.servicesystem')),
            ],
        ),
        migrations.CreateModel(
            name='BackupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_schedule', models.TextField()),
                ('backup_location', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.servicesystem')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='service_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.servicesystem'),
        ),
    ]
