# Generated by Django 4.2.15 on 2024-08-18 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='containerization',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='dependency',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='deploymenttool',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='monitoringtool',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='scalingconfiguration',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
