# Generated by Django 4.2.15 on 2024-08-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_rename_update_at_application_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(),
        ),
    ]
