# Generated by Django 4.2.15 on 2024-08-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_alter_application_name_alter_dependency_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesystem',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
