# Generated by Django 4.2.15 on 2024-08-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_alter_application_name_alter_dependency_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependency',
            options={'verbose_name_plural': 'Dependencies'},
        ),
        migrations.AlterModelOptions(
            name='disasterrecovery',
            options={'verbose_name_plural': 'DisasterRecoveries'},
        ),
    ]
