# Generated by Django 4.2.15 on 2024-08-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentdetails',
            options={'verbose_name_plural': 'Incident Details'},
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='incident',
            new_name='incident_id',
        ),
        migrations.RenameField(
            model_name='incidenttimeline',
            old_name='incident',
            new_name='incident_id',
        ),
    ]
